@echo off
echo [1/3] Dedupe + enrich KB...
node dedupe_kb.js
echo [2/3] (Optional) Delete index lama...
REM curl -X DELETE "http://localhost:7700/indexes/knowledgebase" -H "Authorization: Bearer masterKey"
echo [3/3] Push batch ke Meilisearch...
node tools/push_batch_meili.js
pause
